server:
  port: 80
  servlet:
    context-path: /shortestPath
spring:
  datasource:
    url: jdbc:mysql://47.106.108.49:3306/sep_path?serverTimezone=UTC
    username: path14
    password: sep2314#
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true